# Generated by Django 4.2.2 on 2023-07-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.FloatField(default=0.0)),
                ('maximum', models.FloatField(default=0.0)),
                ('threshold', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='odds_favorite',
        ),
        migrations.RemoveField(
            model_name='match',
            name='odds_opponent',
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='odds_favorite',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='odds_opponent',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='score_favorite',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='score_opponent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='ruleset_favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_favorite', to='matches.ruleset'),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='ruleset_opponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_opponent', to='matches.ruleset'),
        ),
    ]
