# Generated by Django 4.2.2 on 2023-07-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_ruleset_remove_match_odds_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedmap',
            name='map_score_favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='map_score_opponent',
            field=models.IntegerField(default=0),
        ),
    ]
