# Generated by Django 4.2.2 on 2023-07-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_predictedmap_map_score_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmap',
            name='map_score_favorite',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='map_score_opponent',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='odds_favorite',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='odds_opponent',
            field=models.FloatField(default=3.25),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='ruleset_favorite',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_favorite', to='matches.ruleset'),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='ruleset_opponent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_opponent', to='matches.ruleset'),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='score_favorite',
            field=models.FloatField(default=120.0),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='score_opponent',
            field=models.FloatField(default=140.0),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='maximum',
            field=models.FloatField(default=200.0),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='threshold',
            field=models.FloatField(default=130.0),
        ),
    ]
