# Generated by Django 4.2.2 on 2023-07-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_predictedmap_map_score_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmap',
            name='ruleset_favorite',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_favorite', to='matches.ruleset'),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='ruleset_opponent',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_opponent', to='matches.ruleset'),
        ),
    ]
