# Generated by Django 4.2.2 on 2023-07-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_odds_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='pref',
            field=models.CharField(default='010_01000_0_0', max_length=20),
        ),
    ]
