# Generated by Django 4.2.2 on 2023-07-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_remove_team_id_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmap',
            name='ruleset_favorite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_favorite', to='matches.ruleset'),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='ruleset_opponent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ruleset_opponent', to='matches.ruleset'),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='score_favorite',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='score_opponent',
            field=models.FloatField(default=None, null=True),
        ),
    ]
