# Generated by Django 4.2.2 on 2023-07-08 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_predictedmap_ruleset_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
