# Generated by Django 4.2.2 on 2023-07-10 07:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_alter_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedmap',
            name='banned_when_could',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='bookmakers_spread',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='certainty_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='comfortability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='map_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='map_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.5, 0.5], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='map_streak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='map_winrate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.5, 0.5], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='opponent_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.5, 0.5], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='percentage_of_played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='picked_to_played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='prematch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='previous_map_offset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.5, 0.5], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='previous_map_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.5, 0.5], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='recent_performance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.5, 0.5], size=2),
        ),
        migrations.AddField(
            model_name='predictedmap',
            name='streak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.0, 0.0], size=2),
        ),
    ]
