# Generated by Django 4.2.2 on 2023-07-10 07:48

import django.contrib.postgres.fields
from django.db import migrations, models
import matches.models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_predictedmap_banned_when_could_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmap',
            name='banned_when_could',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='map_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='map_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='map_streak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='map_winrate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='opponent_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='percentage_of_played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='picked_to_played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='previous_map_offset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='previous_map_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='recent_performance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='streak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=matches.models.default_map_stat_normalized, size=2),
        ),
    ]
