# Generated by Django 4.2.2 on 2023-07-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_alter_predictedmap_banned_when_could_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedmap',
            name='bookmakers_spread',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='certainty_change',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='comfortability',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='predictedmap',
            name='prematch',
            field=models.FloatField(default=0.5),
        ),
    ]
