# Generated by Django 4.2.2 on 2023-07-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_alter_predictedmap_bookmakers_spread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='related_map',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='matches.predictedmap'),
        ),
    ]
