# Generated by Django 4.2.2 on 2023-07-27 02:27

from django.db import migrations, models
import nerif_vercel.storages


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(storage=nerif_vercel.storages.RemoteStorage(), upload_to='profile_images/'),
        ),
    ]
