# Generated by Django 4.2.2 on 2023-07-27 00:53

from django.db import migrations, models
import nerif_vercel.storages


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(storage=nerif_vercel.storages.RemoteStorage(), upload_to='blog/covers/'),
        ),
    ]
